In [1]:
import game_connect4
import numpy as np

game = game_connect4.Connect4()

In [2]:
game.print_gameboard()

game.gameboard = np.array([  [ 0,  0,  0,  0,  0,  0,  0],
                             [ 0,  0,  0,  0,  0,  0,  0],
                             [ 0, -1,  0,  0,  0,  1,  0],
                             [ 0, -1,  0,  0,  1, -1,  0],
                             [ 0, -1,  0,  1,  1, -1,  0],
                             [ 0, -1,  1, -1, -1, -1, -1],
                ])

  0  0  0  0  0  0  0
  0  0  0  0  0  0  0
  0  0  0  0  0  0  0
  0  0  0  0  0  0  0
  0  0  0  0  0  0  0
  0  0  0  0  0  0  0


In [3]:
game.print_gameboard()

  0  0  0  0  0  0  0
  0  0  0  0  0  0  0
  0 -1  0  0  0  1  0
  0 -1  0  0  1 -1  0
  0 -1  0  1  1 -1  0
  0 -1  1 -1 -1 -1 -1


In [4]:
game.coin = -1
print(game.check_connect_4(3, 5))

True


In [5]:
game.coin = 1
print(game.check_connect_4(5, 1))
game.print_gameboard()

curr_x_pos = 5
curr_y_pos = 1
[]
curr_x_pos = 4
curr_y_pos = 2
[]
curr_x_pos = 3
curr_y_pos = 3
[[ 0  0  0  0]
 [ 0  0  0  0]
 [ 0  0  1  0]
 [ 0  1 -1  0]]
curr_x_pos = 2
curr_y_pos = 4
[[ 0  0  0  0]
 [ 0  0  0  1]
 [ 0  0  1 -1]
 [ 0  1  1 -1]]
False
  0  0  0  0  0  0  0
  0  0  0  0  0  0  0
  0 -1  0  0  0  1  0
  0 -1  0  0  1 -1  0
  0 -1  0  1  1 -1  0
  0 -1  1 -1 -1 -1 -1


In [6]:
game.gameboard = np.array([  [ 0,  0,  0,  0,  0,  0,  0],
                             [ 0,  0,  0,  0,  0,  0,  0],
                             [ 0, -1,  1,  0,  0,  1,  0],
                             [ 0, -1, -1,  1,  1, -1,  0],
                             [ 0, -1, -1,  1,  1, -1,  0],
                             [ 0, -1,  1, -1, -1,  1, -1],
                ])

game.print_gameboard()

  0  0  0  0  0  0  0
  0  0  0  0  0  0  0
  0 -1  1  0  0  1  0
  0 -1 -1  1  1 -1  0
  0 -1 -1  1  1 -1  0
  0 -1  1 -1 -1  1 -1


In [7]:
game.coin = 1
print(game.check_connect_4(2, 2))
game.print_gameboard()

True
  0  0  0  0  0  0  0
  0  0  0  0  0  0  0
  0 -1  1  0  0  1  0
  0 -1 -1  1  1 -1  0
  0 -1 -1  1  1 -1  0
  0 -1  1 -1 -1  1 -1


In [8]:
print(game.add_coin(2))
game.print_gameboard()

False
[0 0 0 0 0 0 0]
[0 0 0 0 0 0 0]
[ 0 -1  0  0  0  0  0]
[ 0 -1  0  0  0  0  0]
[ 0 -1  0  0  0  0  0]
[1 1 1 0 0 0 0]


In [9]:
print(game.add_coin(4))
game.print_gameboard()

False
[0 0 0 0 0 0 0]
[0 0 0 0 0 0 0]
[ 0 -1  0  0  0  0  0]
[ 0 -1  0  0  0  0  0]
[ 0 -1  0  0  0  0  0]
[1 1 1 1 0 0 0]
